config/routes.rb
Rails.application.routes.draw do
  get '/artists/search', to: 'artists#search'
  resources :artists, except: [:destroy]
  resources :genres, except: [:destroy]
  resources :songs, except: [:destroy]

  get '/users/search', to: 'users#search'
  resources :users, except: [:destroy]

  post '/playlist/songs', to: 'playlists#add_songs', as: :add_songs_to_playlist
  get '/playlists/owned', to: 'playlists#owned'
  get '/playlists/explore', to: 'playlists#explore'
  get '/playlists/import', to: 'playlists#import'
  post 'playlists/import/:id', to: 'playlists#import_save'
  delete '/playlist/:id/songs', to: 'playlists#delete_songs', as: :delete_songs_from_playlist

  resources :playlists

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/sessions/destroy', to: 'sessions#destroy'
  root 'welcome#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :playlists do
    member do
      get :likes
    end
  end

  resources :playlists do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  get '/auth/facebook/callback' => 'sessions#create'

  post '/search', to: 'songs#search'
  get '/search', to: 'songs#search'
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs

  validates :name, presence: true, uniqueness: true

  searchable do
    text :name
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :require_login
  def index
    @artists = Artist.joins(:songs).group(:id).order(:name).select(:id, :name, "count(*) AS total").page params[:page]
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.valid?
      @artist.save
      redirect_to artist_path(@artist)
    else
      redirect_to new_artist_path
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      redirect_to edit_artist_path(@artist)
    end
  end

  def search
    term = params[:term]
    search = Artist.search do
      fulltext term
    end
    @artists = search.results
    @artists = Artist.joins(:songs).where(id: @artists.pluck(:id)).group(:id).order(:name).select(:id, :name, "count(*) AS total").page params[:page]
    render "artists/index"
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: {class: "ui form"} do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit class: "ui primary button" %>
<% end %>

app/views/artists/_search.html.erb
<%= form_tag artists_search_path, method: :get do %>
    <div class="fluid ui action input">
      <%= text_field_tag :term, nil, placeholder: "Search..." %>
      <button type="submit" class="ui icon orange button">
        <i class="search icon"></i>
      </button>
    </div>
<% end %>
<br>
<% if params[:term] %>
    <p>Showing results for: <strong><%= params[:term] %></strong></p>
<% end %>

app/views/artists/edit.html.erb
<h2 class="ui dividing header">Edit Artist</h2>
<%= render partial: "form", object: @artist %>

app/views/artists/index.html.erb
<h2 class="ui dividing header">Artists</h2>
<%= render partial: "search" %>
<div class="ui divider"></div>
<%= paginate @artists, window: 2 %>
<p><%= link_to "Create new Artist", new_artist_path, class: "ui olive button" %></p>

<table class="ui teal table">
  <thead>
  <tr>
    <th class="three wide">Artist</th>
    <th class="two wide ui center aligned">Total Songs</th>
    <th>Songs</th>
  </tr>
  </thead>
  <tbody>
  <% @artists.each do |artist| %>
    <tr>
      <td><%= link_to artist.name, artist_path(artist) %></td>
      <td class="ui center aligned"><%= artist.total %></td>
      <td><%= artist.songs.limit(3).map(&:title).join(", ") %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/artists/new.html.erb
<h2 class="ui dividing header">New Artist</h2>
<%= render partial: "form", object: @artist %>

app/views/artists/show.html.erb
<h2 class="ui dividing header"><%= @artist.name %></h2>
<p><%= link_to "Edit", edit_artist_path(@artist), class: "ui button" %></p>

<%= render partial: "playlists/add", locals: {songs: @artist.songs} %>

<p><%= link_to "All Artists", artists_path %></p>