config/routes.rb
Rails.application.routes.draw do
  get '/artists/search', to: 'artists#search'
  resources :artists, except: [:destroy]
  resources :genres, except: [:destroy]
  resources :songs, except: [:destroy]

  get '/users/search', to: 'users#search'
  resources :users, except: [:destroy]

  post '/playlist/songs', to: 'playlists#add_songs', as: :add_songs_to_playlist
  get '/playlists/owned', to: 'playlists#owned'
  get '/playlists/explore', to: 'playlists#explore'
  get '/playlists/import', to: 'playlists#import'
  post 'playlists/import/:id', to: 'playlists#import_save'
  delete '/playlist/:id/songs', to: 'playlists#delete_songs', as: :delete_songs_from_playlist

  resources :playlists

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/sessions/destroy', to: 'sessions#destroy'
  root 'welcome#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :playlists do
    member do
      get :likes
    end
  end

  resources :playlists do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  get '/auth/facebook/callback' => 'sessions#create'

  post '/search', to: 'songs#search'
  get '/search', to: 'songs#search'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :playlists, dependent: :destroy
  has_many :playlist_songs, through: :playlists
  has_many :songs, through: :playlist_songs
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key:"followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, :dependent => :delete_all
  has_many :liked_playlists, :through =>  :likes, :source => :playlist
  has_many :comments

  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true

  has_secure_password

  searchable do
    text :name
    text :email
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def gravatar_hash
    Digest::MD5.hexdigest self.email
  end

  def self.from_omniauth(auth)
    where(uid: auth.uid).new do |user|
      user.email = auth.info.email
      user.name = auth.info.name
    end
  end


end

app/controllers/users_controller.rb
class UsersController<ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:new, :create]

  def index
    @users= User.order(:name).includes(:playlists).page params[:page]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params(:name, :email, :password, :password_confirmation, :spotify_username))
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :'/users/new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.update(user_params(:name, :email, :spotify_username))
    redirect_to user_path(@user)
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  def search
    @users = User.search { fulltext params[:term] }.results
    render "users/index"
  end

  private
  def user_params(*args)
    params.require(:user).permit(*args)
  end

end

app/views/users/_card.html.erb
<div class="card">
  <%= link_to image_tag("http://gravatar.com/avatar/#{user.gravatar_hash}?s=300"), user_path(user), class: "image" %>
  <div class="content">
    <div class="header"><%= user.name %></div>
    <div class="meta">
      <%= current_user.following?(user) ? "You Follow" : "You currently don't follow" %>
    </div>
    <div class="description">
      <%= user.name %> has <%= pluralize(user.playlists.count, "playlist") %>.
    </div>
  </div>
  <div class="extra content" style="min-height: 50.17px !important;">
    <span class="right floated">
      Joined in <%= user.created_at.year %>
    </span>
    <% if current_user.following?(user) %>
        <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
                     html: {method: :delete}) do |f| %>
            <%= f.hidden_field :unfollow_user_id, :value => user.id %>
            <%= f.submit "Unfollow", class: "mini ui button" %><br>
        <% end %>
    <% elsif current_user.id != user.id %>
        <%= form_for(current_user.active_relationships.build) do |f| %>
            <div><%= hidden_field_tag :followed_id, user.id %></div>
            <%= f.submit "Follow", class: "mini ui button" %><br>
        <% end %>
    <% end %>
  </div>
</div>

app/views/users/_follow.html.erb
<br>
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "ui primary button" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == (@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_search.html.erb
<%= form_tag users_search_path, method: :get do %>
    <div class="fluid ui action input">
      <%= text_field_tag :term, nil, placeholder: "Search..." %>
      <button type="submit" class="ui icon orange button">
        <i class="search icon"></i>
      </button>
    </div>
<% end %>
<br>
<% if params[:term] %>
    <p>Showing results for: <strong><%= params[:term] %></strong></p>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
             <%=f.hidden_field :unfollow_user_id, :value => @user.id%>
  <%= f.submit "Unfollow", class: "ui red button" %>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user, html: {class: "ui form"} do |f| %>
    <div class="five wide field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="five wide field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="five wide field">
      <%= f.label :spotify_username %>
      <%= f.text_field :spotify_username %>
    </div>
    <%= f.submit class: "ui green button" %>
<% end %>

app/views/users/index.html.erb
<h2 class="ui dividing header">All Users</h2>
<%= render partial: "users/search" %>
<div class="ui divider"></div>
<div style="margin-bottom: 50px;">
  <%= paginate @users, window: 2 %>
</div>
<div class="ui clearing divider"></div>
<div class="ui link cards">
  <% @users.each do |user| %>
      <%= render partial: "card", locals: {user: user} %>
  <% end %>
</div>

app/views/users/new.html.erb
<%= form_for @user, html: {class: "ui form"} do |f| %>
    <div class="five wide field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="five wide field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="five wide field">
      <%= f.label :spotify_username %>
      <%= f.text_field :spotify_username %>
    </div>
    <div class="five wide field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="five wide field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <%= f.submit class: "ui green button" %>
<% end %>

app/views/users/show.html.erb
<div class="profile">
  <div style="float: left">
    <img class="ui small circular image" style="width: 110px;height:110px" src="http://gravatar.com/avatar/<%= @user.gravatar_hash %>?s=200">
  </div>
  <div>
    <h1 class="ui dividing header"><%= @user.name %> </h1><br>
    <div class="ui compact menu">
      <a class="item" href="<%= following_user_path(@user) %>">
        <i class="icon user"></i> Following
        <div class="floating ui red label"><%= @user.following.count %></div>
      </a>
      <a class="item" href="<%= followers_user_path(@user) %>">
        <i class="icon users"></i> Followers
        <div class="floating ui teal label"><%= @user.followers.count %></div>
      </a>
      <%= link_to "Edit Your Profile", edit_user_path(@user), class: "item" if @user.id == current_user.id %>
    </div>
    <%= render 'follow_form' unless @user.id == current_user.id %>
  </div>
</div>
<div class="clearing playlists" style="margin-top: 50px">
  <div class="ui cards">
    <% @user.playlists.each do |playlist| %>
        <%= render partial: "playlists/playlist", locals: {playlist: playlist, color: "olive"} %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<h1><%= @title.capitalize %></h1>

<h2><%= @user.name %></h2>
<%= link_to "View My Profile", @user %><br><br><br>

<% if @users.any? %>
    <div class="ui link cards">
      <% @users.each do |user| %>
          <%= render partial: "card", locals: {user: user} %>
      <% end %>
    </div>
<% end %>