config/routes.rb
Rails.application.routes.draw do
  get '/artists/search', to: 'artists#search'
  resources :artists, except: [:destroy]
  resources :genres, except: [:destroy]
  resources :songs, except: [:destroy]

  get '/users/search', to: 'users#search'
  resources :users, except: [:destroy]

  post '/playlist/songs', to: 'playlists#add_songs', as: :add_songs_to_playlist
  get '/playlists/owned', to: 'playlists#owned'
  get '/playlists/explore', to: 'playlists#explore'
  get '/playlists/import', to: 'playlists#import'
  post 'playlists/import/:id', to: 'playlists#import_save'
  delete '/playlist/:id/songs', to: 'playlists#delete_songs', as: :delete_songs_from_playlist

  resources :playlists

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/sessions/destroy', to: 'sessions#destroy'
  root 'welcome#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :playlists do
    member do
      get :likes
    end
  end

  resources :playlists do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  get '/auth/facebook/callback' => 'sessions#create'

  post '/search', to: 'songs#search'
  get '/search', to: 'songs#search'
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_songs, dependent: :destroy
  has_many :songs, through: :playlist_songs
  has_many :likes, :dependent => :delete_all
  has_many :liking_users, :through => :likes, :source => :user
  has_many :comments, :as => :commentable

  include PublicActivity::Model
  tracked only: [:create], owner: :user

  validates :name, presence: true

  def like(user)
    likes << Like.new(user_id: user.id)
  end

  def unlike(user)
    likes.where(user_id: user.id).first.destroy
  end

  def liked?(user)
    likes.include?(user.id)
  end

end

app/controllers/playlists_controller.rb
class PlaylistsController<ApplicationController
  before_action :require_login

  def index
    @my_playlists = Playlist.where(user: current_user).limit(5)
    @others_playlists = Playlist.where.not(user: current_user).sample(5)
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user_id = current_user.id
    if @playlist.save
      redirect_to playlist_path(@playlist)
    else
      redirect_to new_playlist_path
    end
  end

  def show
    @playlist = Playlist.find_by(id: params[:id])
    @songs = Song.joins(:playlist_songs).where(playlist_songs: {playlist: @playlist}).includes(:artist).includes(:genres).page params[:page]
    @like = Like.new
    @comment = @playlist.comments.new
  end

  def destroy
    Playlist.find(params[:id]).destroy
    redirect_to playlists_path
  end

  def edit
    @playlist = Playlist.find_by(id: params[:id])
  end

  def update
    @playlist = Playlist.find_by(id: params[:id])
    @playlist.update(playlist_params)
    redirect_to playlist_path(@playlist)
  end

  def add_songs
    @playlist = Playlist.find_by(id: params[:playlist][:id], user: current_user)
    song_ids = (params[:playlist][:song_ids].map(&:to_i) + @playlist.song_ids).uniq if @playlist && params[:playlist]

    if @playlist && @playlist.update(song_ids: song_ids)
      redirect_to playlist_path(@playlist)
    else
      flash[:messages] = ["Playlist not found."]
      redirect_to songs_path
    end
  end

  def delete_songs
    @playlist = Playlist.find_by(id: params[:id], user: current_user)

    song_ids = @playlist.song_ids
    if params[:playlist]
      song_ids -= params[:playlist][:song_ids].map(&:to_i)
    end

    unless @playlist && @playlist.update(song_ids: song_ids)
      flash[:messages] = ["Playlist not found."]
    end

    redirect_to playlist_path(@playlist)
  end

  def likes
    @playlist = Playlist.find_by(id: params[:id])
    @likes = @playlist.likes
    render 'show_like'
  end

  def owned
    @playlists = current_user.playlists.page params[:page]
    render 'paginated', locals: {color: "pink", title: "My Playlists"}
  end

  def explore
    @playlists = Playlist.where.not(user: current_user).page params[:page]
    render 'paginated', locals: {color: "purple", title: "Explore Playlists"}
  end

  def import
    if current_user.spotify_username.nil?
      flash[:messages] = ["You need to add your Spotify username"]
      redirect_to edit_user_path(current_user)
    else
      spotify_api = SpotifyApi.new
      @playlists = spotify_api.client.user_playlists(current_user.spotify_username)["items"]
    end
  end

  def import_save
    spotify_api = SpotifyApi.new
    @playlist = spotify_api.client.user_playlist(params[:spotify_username], params[:id])
    tracks = spotify_api.client.user_playlist_tracks(params[:spotify_username], params[:id])
    tracks_to_import = tracks["items"].collect do |item|
      {
        :artist_name => item["track"]["artists"].first["name"],
        :title => item["track"]["name"],
        :spotify_id => item["track"]["id"]
      }
    end
    playlist = Playlist.new(name: @playlist["name"], user: current_user)
    tracks_to_import.each do |track|
      song = Song.find_or_initialize_by(spotify_id: track[:spotify_id])
      song.update(track)
      playlist.songs << song
    end
    playlist.save
    redirect_to playlist_path(playlist.id)
  end

  private
  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/views/playlists/_add.html.erb
<%= form_for :playlist, url: add_songs_to_playlist_path, html: {class: "ui form"} do |f| %>
    <table class="ui teal table">
      <thead>
      <tr>
        <th class="one wide">Select</th>
        <th class="three wide">Title</th>
        <th class="three wide">Artist</th>
        <th class="two wide">Genre</th>
        <th>Playlists</th>
      </tr>
      </thead>
      <tbody>
      <% songs.each do |song| %>
          <tr>
            <td class="center aligned">
              <div class="ui checkbox">
                <input type="checkbox" name="playlist[song_ids][]" class="ui checkbox" value="<%= song.id %>">
              </div>
            </td>
            <td><%= link_to song.title, song_path(song) %></td>
            <td><%= link_to song.artist.name, artist_path(song.artist) %></td>
            <td><%= song.genres.map(&:name).join(", ") %></td>
            <td>
             <% color = ["red", "orange", "yellow", "olive", "green", "teal", "blue", "violet", "purple", "pink", "brown", "grey", "black"] %>
              <% song.playlists.each do |playlist| %>
                <%= link_to playlist.name, playlist_path(playlist), class: "ui #{color.sample} tag label" %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <div class="three wide field">
      <%= f.label :id, "Playlists" %>
      <%= f.collection_select :id, current_user_playlists, :id, :name, {prompt: true}, {class: "ui search dropdown"} %>
    </div>
    <p><%= submit_tag "Add to selected Playlist", class: "ui teal button" %></p>
<% end %>

app/views/playlists/_form.html.erb
<%= form_for @playlist, html: {class: "ui form"} do |f| %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <%= f.submit class: "ui primary button" %>
<% end %>

app/views/playlists/_like.html.erb
<%@playlist = Playlist.find_by(id: params[:id])%>
<% unless current_user == (@user) %>
  <% if @playlist.likes != [] && @playlist.likes.find {|like| like.user_id == current_user.id}%>
    <%= form_for(@playlist.likes.find_by(user_id: current_user.id),
               html: { method: :delete }) do |f| %>
               <%=f.hidden_field :user_id, :value => current_user.id%>
               <%=f.hidden_field :playlist_id, :value => @playlist.id%>
    <%= f.submit "Unlike", class: "ui primary button" %>
  <% end %>
  <% else %>
  <%= form_for(@playlist.likes.build) do |f| %>

    <div><%= hidden_field_tag :user_id, current_user.id %></div>
    <%=hidden_field_tag :playlist_id, @playlist.id%>
    <%= f.submit "Like", class: "ui primary button" %>
  <% end %>
  <% end %>

<% end %>

app/views/playlists/_playlist.html.erb
<div class="card">
  <div class="content">
    <div class="header"><%= playlist.name %></div>
    <div class="meta"><i class="user outline icon"></i><i>Curated by</i> <%= playlist.user.try(:name) %></div>
    <div class="description">
      <ul class="">
        <li><i class="music icon"></i><%= pluralize(playlist.songs.count, "song") %></li>
        <li><i class="heart icon"></i><%= pluralize(playlist.likes.count, "like") %></li>
      </ul>
    </div>
  </div>
  <%= link_to "<i class=\"eye icon\"></i> See Playlist".html_safe, playlist_path(playlist), class: "ui #{color} bottom attached button" %>
</div>

app/views/playlists/edit.html.erb
<%=render 'form'%>

app/views/playlists/import.html.erb
<h2 class="ui dividing header">Playlists for <%= current_user.spotify_username %></h2>
<div class="ui cards">
  <% @playlists.each do |playlist| %>
      <div class="card">
        <div class="content">
          <div class="header"><%= playlist["name"] %></div>
          <div class="meta"><i class="user outline icon"></i><i>Curated by</i> <%= playlist["owner"]["display_name"] %></div>
          <div class="description">
            <ul class="">
              <li><i class="music icon"></i><%= pluralize(playlist["tracks"]["total"], "song") %></li>
              <li><i class="file icon"></i><%= playlist["id"] %></li>
            </ul>
          </div>
        </div>
        <%= form_tag "/playlists/import/#{playlist["id"]}", method: :post do %>
            <%= hidden_field_tag :spotify_username, playlist["owner"]["id"] %>
          <%= submit_tag "[+] Import Playlist".html_safe, class: "fluid ui olive bottom attached button" %>
        <% end %>
      </div>
<% end %>
</div>

app/views/playlists/index.html.erb
<h2 class="ui dividing header">All Playlists</h2>
<p>
  <%= link_to "Create a New Playlist", new_playlist_path, class: "ui button" %>
  <%= link_to "Import playlist from Spotify", playlists_import_path, class: "ui green button" %>
</p>

<h3 class="ui dividing header">My Playlists</h3>
<div class="ui cards">
  <% @my_playlists.each do |my_playlist| %>
      <%= render partial: "playlist", locals: {playlist: my_playlist, color: "pink"} %>
  <% end %>
</div>
<br>
<%= link_to "<i class=\"folder open outline icon\"></i>See all my playlists".html_safe,
            playlists_owned_path, class: "ui orange button" %>
<h3 class="ui dividing header">Explore Playlists</h3>

<div class="ui cards">
  <% @others_playlists.each do |other_playlist| %>
      <%= render partial: "playlist", locals: {playlist: other_playlist, color: "purple"} %>
  <% end %>
</div>
<br>
<%= link_to "<i class=\"world icon\"></i>Explore playlists".html_safe, playlists_explore_path,
            class: "ui orange button" %>

app/views/playlists/new.html.erb
<%=render 'form'%>

app/views/playlists/paginated.html.erb
<h2 class="ui dividing header"><%= title %></h2>
<%= paginate @playlists, window: 2 %>
<div class="ui divider" style="margin-top: 55px"></div>
<br>
<div class="ui cards">
  <% @playlists.each do |playlist| %>
      <%= render partial: "playlist", locals: {playlist: playlist, color: color} %>
  <% end %>
</div>

app/views/playlists/show.html.erb
<h1 class="ui dividing header"><%= @playlist.name %></h1>
<%= paginate @songs, window: 2 %><p><em>Created By: <%= @playlist.user.name if @playlist.user%></em></p>

<% unless @songs.empty? %>
    <%= form_for @playlist, url: delete_songs_from_playlist_path, html: {class: "ui form"}, method: :delete do |f| %>
        <table class="ui teal table">
          <thead>
          <tr>
            <th class="one wide">Select</th>
            <th class="three wide">Title</th>
            <th class="three wide">Artist</th>
            <th>Genre</th>
          </tr>
          </thead>
          <tbody>
          <% @songs.each do |song| %>
              <tr>
                <td class="center aligned">
                  <input type="checkbox" name="playlist[song_ids][]" value="<%= song.id %>">
                </td>
                <td><%= link_to song.title, song_path(song) %></td>
                <td><%= link_to song.artist.name, artist_path(song.artist) %></td>
                <td><%= song.genres.map(&:name).join(", ") %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <p><%= submit_tag "Delete selected from Playlist", class: "ui red button" %></p>
    <% end %>
<% end %>
<% if @playlist.user == current_user %>
    <div class="ui divider"></div>
    <%= link_to "Edit this Playlist", edit_playlist_path(@playlist), class: "ui button" %>
    <%= link_to "Delete this Playlist", playlist_path(@playlist), method: "DELETE", class: "ui red button" %>
<% else %>
    <%= render 'like' %>
<% end %><br>

<%= link_to @playlist.likes.count, likes_playlist_path(@playlist) %> Likes
<div class="ui comments">
  <h3 class="ui dividing header">Comments</h3>
<%if @playlist.comments%>
  <div class="comment">
<p><%=render :partial => 'comments/new', locals: {comment: @comment}%>
<ul class="comment_list">
  <%=render :partial => 'comments/comment', :collection => @playlist.comments%>
  <%end%>
</ul>
</div>

app/views/playlists/show_like.html.erb
<h1>Likes</h1>

<h2><%= @playlist.name %></h2>
<p><%= link_to "View The Playlist", @playlist, class: "ui olive button" %></p>


<div>
  <% if @likes.any? %>
    <div class="ui cards">
      <% @likes.each do |like| %>
          <%= render partial: "users/card", locals: {user: like.user} %>
      <% end %>
    </div>
<% else %>
    No likes yet!
<% end %>
</div>