config/routes.rb
Rails.application.routes.draw do
  get '/artists/search', to: 'artists#search'
  resources :artists, except: [:destroy]
  resources :genres, except: [:destroy]
  resources :songs, except: [:destroy]

  get '/users/search', to: 'users#search'
  resources :users, except: [:destroy]

  post '/playlist/songs', to: 'playlists#add_songs', as: :add_songs_to_playlist
  get '/playlists/owned', to: 'playlists#owned'
  get '/playlists/explore', to: 'playlists#explore'
  get '/playlists/import', to: 'playlists#import'
  post 'playlists/import/:id', to: 'playlists#import_save'
  delete '/playlist/:id/songs', to: 'playlists#delete_songs', as: :delete_songs_from_playlist

  resources :playlists

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/sessions/destroy', to: 'sessions#destroy'
  root 'welcome#index'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :playlists do
    member do
      get :likes
    end
  end

  resources :playlists do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  get '/auth/facebook/callback' => 'sessions#create'

  post '/search', to: 'songs#search'
  get '/search', to: 'songs#search'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :current_user_playlists, :require_login
  include PublicActivity::StoreController

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user == nil
  end

  def current_user_playlists
    Playlist.where(user: current_user)
  end

  def require_login
    redirect_to login_path unless session.include? :user_id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<div class="ui menu inverted">
  <div class="active blue item">
    Flatiron Playlist
  </div>
  <%= link_to "Home", root_path, class: "item" %>
  <% if current_user && current_user.id %>
      <%= link_to "Songs", songs_path, class: "item" %>
      <%= link_to "Artists", artists_path, class: "item" %>
      <%= link_to "Genres", genres_path, class: "item" %>
      <%= link_to "Playlists", playlists_path, class: "item" %>
      <%= link_to "Users", users_path, class: "item"%>
      <%= link_to "My Account", user_path(current_user), class: "item" %>
      <%= link_to "Log Out", sessions_destroy_path, method: "DELETE", class: "item" %><br>
  <% else %>
      <%= link_to "Sign Up", new_user_path, class: "item" %>
      <%= link_to "Log In", login_path, class: "item" %>
  <% end %>
</div>